name: wazo-plugind-prometheus
namespace: potoo
version: 0.0.2
author: Benoît Stahl
display_name: wazo-plugind-prometheus-local
description: This plugin enable and expose asterisk's prometheus endpoint 
homepage: https://github.com/benasse/wazo-plugind-prometheus-local
debian_depends:
 - autoconf
 - autoconf-archive
 - autogen
 - automake
 - cmake
 - libelf-dev
 - libjson-c-dev
 - libjudy-dev
 - liblz4-dev
 - libmnl-dev
 - libssl-dev
 - libtool
 - libuv1-dev
 - pkg-config
 - uuid-dev
 - zlib1g-dev
